version: '3.8'

services:
  # PHP Service
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    volumes:
      - ./src:/var/www/html/

  # Database Service (MySQL 8.0)
  database:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      # value gotten from a .env file 
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USERNAME: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql

  # PHPMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-container
    restart: always
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: secret # Must match the root password defined for the MySQL service
    ports:
      - "8080:80"
    depends_on:
      - database

volumes:
  db-data: # Anonymous volume declaration
